### ISSUE TITLE
Support for MySQL Bit-Value Type - BIT

### ISSUE THREAD

**Issue by bmcjarrow** [osalvador/ReplicaDB#106]
When Replicating a table between MySQL servers the value for the Bit type gets converted from a zero to a one.
Server1
mysql radman -e "select id,name,description,cast(sensitive_data as UNSIGNED) as sensitive_data from radcheck_attribute"
+----+-----------+-------------+----------------+
| id | name      | description | sensitive_data |
+----+-----------+-------------+----------------+
|  2 | Auth-Type |             |              0 |
+----+-----------+-------------+----------------+

Server2
mysql radman -e "select id,name,description,cast(sensitive_data as UNSIGNED) as sensitive_data from radcheck_attribute"
+----+-----------+-------------+----------------+
| id | name      | description | sensitive_data |
+----+-----------+-------------+----------------+
|  2 | Auth-Type |             |              1 |
+----+-----------+-------------+----------------+

CREATE TABLE `radcheck_attribute` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `sensitive_data` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_radcheck_attribute_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1

**Comment by bmcjarrow** [comment]
issue solved with https://github.com/osalvador/ReplicaDB/pull/113

**Comment by osalvador** [comment]
Thank you very much @bmcjarrow
