### ISSUE TITLE
postgresql to postgresql data base

### ISSUE THREAD

**Issue by aguerrave** [osalvador/ReplicaDB#110]
Can I use the tool for the entire database?

**Comment by MichalisDBA** [comment]
For now you can select one table at a time or use this script tweaked to your needs:

https://github.com/osalvador/ReplicaDB/issues/27#issuecomment-862229297

**Comment by osalvador** [comment]
Hi, 

Replicate the entire database is a complex process, because sometimes each table has it's own properties.

For the moment you can move forward with what @MichalisDBA has said.

Thanks!
