### ISSUE TITLE
question:What's the difference from ora2pg?

### ISSUE THREAD

**Issue by prensgold** [osalvador/ReplicaDB#126]
We are planning to move a data close to 2tb from oracle to postgresql.
we are looking for a fast solution.
We do not want to do streaming replication.
but we cannot stay offline for a long time.
How logical is it to plan the following migration with your tool?
initial load + incremental (several times per migration) 
.
How does the incremental feature work?
What advantages does it have over ora2pg?

**Comment by osalvador** [comment]
Hi @prensgold 

- `We are planning to move a data close to 2tb from oracle to postgresql.`. Interesting.
- `we are looking for a fast solution.`. Here is ReplicaDB.
- `We do not want to do streaming replication`. ReplicaDB does not support streaming replication.
- `but we cannot stay offline for a long time.`. Ok.
- `How logical is it to plan the following migration with your tool? initial load + incremental (several times per migration)`
  - Yes, I think this is the best strategy. But some recommendations: 
     - Test your replication in preproduction environments. 
     - Create the sink table without indexes. When the first replication is finished, create the indexes.
     - For the first replication, use the `complete` mode with `sink.disable.escape=true` for better performance. If you have `\n` or `\r` values you can't disable escape. 
     - Place the ReplicaDB binary program as close as possible to the database sink, reducing network latency. Even on the same machine where the Postgres database sink is running. This greatly reduces network traffic and increases considerably performance. 
     - Use parallel jobs. Start with 4 or 6, depending on the database resources and increase accordingly to determine the best parallelism parameter. Each job is a new connection to the postgres database. 
     - Use partitions in the sink table by date.
     - Remember, incremental mode needs a PK on the sink table and you must know the last incremental value and pass it as a parameter to the source query.

- `How does the incremental feature work?`. https://osalvador.github.io/ReplicaDB/docs/docs.html#incremental
- `What advantages does it have over ora2pg?`. 
   - ora2pg aims to be a complete schema and data migration tool between Oracle and Postgres only. 
   - ReplicaDB aims to be a data replication tool, for any database, with different replication modes (full, atomic and incremental). 
   - The main goal of ReplicaDB is performance over extra capabilities. 
   - In incremental replication, ReplicaDB updates records per PK. 
   - ReplicaDB and ora2pg are better together

Best Regards!
