### ISSUE TITLE
Image for Container

### ISSUE THREAD

**Issue by FrancescoTekapp** [osalvador/ReplicaDB#13]
Hi @osalvador ,

I really appreciate your work regarding ReplicaDB.

Could I suggest (and eventually help to mantain) an image for container (Podman / Docker / etc) of your application?

I think It may be a nice feature easy to implement, but It coudl help people to deploy fast your solution.

What do you think?

**Comment by osalvador** [comment]
Hi @FrancescoTekapp,

I think it is a great suggestion. Although it is true, ReplicaDB is very easy to install, but a docker image will help when the infrastructure is in the cloud.

Help will always be welcome. I will start this week to make the first version of the Dockerfile and upload it to dockerhub.

Regards!

**Comment by FrancescoTekapp** [comment]
Hello @osalvador, very happy for your consideration.

ReplicaDB is very easy to deploy and to configure, but I think an image for container could help in development and also production enviroment.

I create a test image from a container base on openjdk and it is ok; i will check your dockerfile and I will be happy to help.
