### ISSUE TITLE
[Windows] "A Java Exception has ocurred"

### ISSUE THREAD

**Issue by DevDorrejo** [osalvador/ReplicaDB#132]
**Describe the bug**
show "A Java Exception has ocurred"

**To Reproduce**
Steps to reproduce the behaviour:
1. Download Replica With oracle
2. Try to open it
3.  "A Java Exception has ocurred"

**Comment by osalvador** [comment]
hi @DevDorrejo 

You must use the command line as explained in the documentation. 

Thanks!
