### ISSUE TITLE
Filter log only with specific severity or higher [enhancement]

### ISSUE THREAD

**Issue by atiris** [osalvador/ReplicaDB#133]
**Describe the enhancement**
I use replicadb in scripts and want to show only errors. 
Any filter for this is not available now. In output I see many INFO and WARN logs.

**To Reproduce**
Any replicadb command to copy data.

**Expected behavior**
Parameter like --log-severity=warn ... or --log-severity=warn,error .. or --silent (something to show only warn and errors, or only errors)

**Additional context**
I use it to migrate a firebird database to postgresql and I get a lot of reports that it doesn't have a jdbc driver and want use custom, but in the end everything goes without problems so too many INFO and WARN for nothing.

**Comment by osalvador** [comment]
Hi @atiris 

Could you try with the parameter `verbose=ERROR` in the ReplicaDB options-file? 

This is and undocumented feature. 
Thanks!
