### ISSUE TITLE
PostgreSQL to MariaDB: java.sql.SQLNonTransientConnectionException: Connection reset

### ISSUE THREAD

**Issue by webtekindo** [osalvador/ReplicaDB#140]
Hi and thank you for this great tool.

Our source is a PostgreSQL database and our sink is MariaDB 10.5. We are using complete-atomic mode.

While syncing small tables it's working perfectly, but we have one table which contains over 40M rows, which is causing error while running replicaDB:

`2023-06-01 00:19:50,519 INFO  SqlManager:430 Inserting data from staging table to sink table within a transaction:  INSERT INTO product_external_fitting...`
`2023-06-01 02:19:57,100 ERROR ReplicaDB:134 Got exception running ReplicaDB: java.sql.SQLNonTransientConnectionException: (conn=1514619) Connection reset`

In the MySQL log we see:

`2023-06-01  0:44:51 1514619 [Warning] Aborted connection 1514619 to db: '*********' user: '********' host: '*********' (Got timeout reading communication packets)
`

Notice the error "ReplicaDB: java.sql.SQLNonTransientConnectionException: Connection reset" always happens after 2 hours exactly, which match the config of **tcp_keepalive_time** on our client server. If we increase to **tcp_keepalive_time** 3 hours then the error happens at 3 hours exactly.

While monitoring the query on the sink server, the query "INSERT INTO product_external_fitting" only took 10 minutes to execute, then the mysql process get in **Sleep** state, then **Killed Reset for next** then mysql process disappear from mysql monitor while the replicaDB script on the client still running without error until it reached **tcp_keepalive_time**.

We already make sure that our MySQL setting are not the issue:

wait_timeout = 28800
max_allowed_packet = 10GB

Do you know what may cause the issue?

Thank you,

Samy

**Comment by osalvador** [comment]
Closed due to inactivity
