### ISSUE TITLE
Running on Windows under cgywin

### ISSUE THREAD

**Issue by asif-rashid** [osalvador/ReplicaDB#153]
**Describe the bug**
I am getting following error message,

Error: Could not find or load main class org.replicadb.ReplicaDB
Caused by: java.lang.ClassNotFoundException: org.replicadb.ReplicaDB

**To Reproduce**
I followed instructions from the docs,

$ curl -o ReplicaDB-0.15.1.tar.gz -L "https://github.com/osalvador/ReplicaDB/releases/download/v0.15.1/ReplicaDB-0.15.1.tar.gz"
$ tar -xvzf ReplicaDB-0.15.1.tar.gz
$ ./bin/replicadb --help

**Expected behavior**
I should see a help message. 

**Additional context**
I have windows 11 pro, MS Windows Terminal 1.17, and cgywin.

**Comment by osalvador** [comment]
Hi @asif-rashid,

I have never used `cgwin`, but on Windows you should use the script `replicadb.cmd` instead of `replicadb` which is intended for linux. 

Regards!
