### ISSUE TITLE
How to give where condition in "source.where"

### ISSUE THREAD

**Issue by hanumanbabushaik** [osalvador/ReplicaDB#173]
**Describe the bug**
How to give where condition in "source.where" condition, I have attached the sample code below.

```
source.where="where AccessLevels.Id!=0"
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Source table DDL
2. Sink table DDL
3. ReplicaDB configuration `options-file`. 

**Expected behavior**

**Additional context**
Add any other context about the problem here. Running environment (cloud, on premise, java version..), source and sink technologies (Oracle, MySQL, Postgres...)

**Comment by MichalisDBA** [comment]
Just like you write a where statement.

For example: `source.where=LAST_UPDATE_DATE >= TO_DATE('01/06/2022','dd/mm/yyyy') AND LAST_UPDATE_DATE < TO_DATE('01/04/2023','dd/mm/yyyy')`
