### ISSUE TITLE
/ FS getting full

### ISSUE THREAD

**Issue by RepallePrabhakar** [osalvador/ReplicaDB#181]
First of all, Thank you so much for the great tool.

Hi,
I am experiencing a strange issue. I am trying to replicate 4M+ rows from Oracle to MariaDB. The issue is that the / File system is getting utilized and eventually full, but I have no idea. Is there anyway that the Replicadb stores the temp data in the / FS? If so, can we change it and how?

Thanks,
Prabha

**Comment by MichalisDBA** [comment]
Hey @RepallePrabhakar. Post your config (without the credentials) to have a look. I have not experienced this issue while i transferred huge amount of data from Oracle to MSSQL.

When you run to that problem what path of the File System was filled up? Did you check?

**Comment by RepallePrabhakar** [comment]
@MichalisDBA, Thanks for the response. Please find the details below 

ReplicaDB is installed, and I am executing the replicate command from the /home/<user> directory, and the sink data directory is /data. When I executed the replicadb using the config file below, I observed that both the file systems / (root) and /data were increasing. 

Please let me know if need any further details.

mode=complete
jobs=40
fetch.size=1000
verbose=true
source.connect=jdbc:oracle:thin:@<hostname>:1529:<sid>
source.user=*********
source.password=**********
source.table=oracle.table
sink.connect=jdbc:mariadb://<ip>:3306/<schema>
sink.user=********
sink.password=*********
sink.table=mariadbtable

**Comment by MichalisDBA** [comment]
@RepallePrabhakar Is your source and the sink database on the same VM? From where you run replicadb? If you have Oracle and MariaDB running on the same VM and try to transfer data with replicadb from the same VM, then it is natural to fill up the disk space. You load data to mariadb.

**Comment by RepallePrabhakar** [comment]
@MichalisDBA , Source, and Sink databases are running on two different VMs. 

I am running replicadb on the sink database server. However, due to insufficient space on the / file system, replication is causing the entire server to hang and eventually fail.How can we avoid using the replicadb from the /root file system, and can we configure it to use another file system?

**Comment by MichalisDBA** [comment]
@RepallePrabhakar I don't think that replicadb stores data anywhere. You can run it from whatever path you like. I think you have not partitioned your disk.

Let's say you have the directory `/data` that inside there are stored the sink database data files. If you haven't partition the disk so that `/data` exists in a seperate partition, then when you load data to the sink with replicadb the root fs `/` will fill up.

Run the command `df -kh` and post the output to see.

**Comment by RepallePrabhakar** [comment]
@MichalisDBA , Please check the below


![image](https://github.com/osalvador/ReplicaDB/assets/23021506/d6659629-40dc-473d-a906-0835ecf95454)

**Comment by MichalisDBA** [comment]
@RepallePrabhakar Check your mariadb `my.cnf` config or configs. 

Try to find the parameter `datadir=`. What path does it have?

If it is `datadir=/data` then the data are stored in `/data` partition.
If it is the default path like `datadir=/var/lib/mysql` then if you do not have `/var` partition, the data will be written to the root fs `/`

**Comment by RepallePrabhakar** [comment]
As I mentioned, I am observing that both the / and MariaDB data directories are filling. For confirmation below is my data directory

![image](https://github.com/osalvador/ReplicaDB/assets/23021506/7f72983e-d59f-40b6-a467-2b817aa95e92)

**Comment by MichalisDBA** [comment]
Try to run replicadb from source server. If the sink server's root fs fills up again, something is not configured right and writes data outside /data partition. Maybe you have defined a tempdir in mariadb that is outside /data partition. Else try to find the path in root fs that fills up to find the culprit.

**Comment by RepallePrabhakar** [comment]
You are absolutely correct. The mariadb was using the /tmp to store these temporary files, which caused the / FS to be full. I have reconfigured it to another FS, and it's working as expected. 

Thank you so much @MichalisDBA
