### ISSUE TITLE
Encryption/Security

### ISSUE THREAD

**Issue by pdevereux** [osalvador/ReplicaDB#19]
What security or encryption is in place for the data in transit?

**Comment by osalvador** [comment]
Hi @pdevereux ,

For data in transit, the encryption used is the one offered by each source and sink driver provider.

For example, for a PostgreSQL source you can use `ssl=true` and `sslmode=require` and for Oracle sink`oracle.net.ssl_version=1.2`. These properties are added as `source.connect.parameter` or` sink.connect.parameter` using the `--options-file` parameter.

https://osalvador.github.io/ReplicaDB/docs/docs.html#32-connecting-to-a-database-server
