### ISSUE TITLE
Incorrect BLOB data copied from MariaDB (LONGBLOB) to PostgreSQL (BYTEA)

### ISSUE THREAD

**Issue by yurybich** [osalvador/ReplicaDB#196]
**Describe the bug**
The source and migrated bytes value doesn't match.

**To Reproduce**
Steps to reproduce the behaviour:
1. Source table DDL (MariaDB)
```
create table t_source (C_BINARY_LONG_BLOB LONGBLOB)
```
2. Sink table DDL (PostgreSQL)
```
create table t_sink(C_BINARY_LONG_BLOB  BYTEA)

```
3. Replicate "t_source" data into "t_sink". 

**Expected behavior**
The binary data in source and target table should be equal.

**Additional context**
Source: MariaDB 10.4
Target: PostgreSQL 16.3

**Comment by yurybich** [comment]
The escape logic was the root cause of incorrectly migrated data.
```
--sink-disable-escape=true
```
was the key to copy the blob content properly in my case.

**Comment by osalvador** [comment]
hmmm binary data should not be escaped. I mark this question as a bug.
