### ISSUE TITLE
How to handle deleted record for incremental load ?

### ISSUE THREAD

**Issue by terrykk** [osalvador/ReplicaDB#22]
As title, thanks

**Comment by osalvador** [comment]
Hi @terrykk,

ReplicaDB replicates a snapshot of the data from a source table, so we cannot get DELETE events. Some strategies involve saving DELETE transactions to another table, based on a trigger from the source table, but all this logic has to be implemented and maintained. This is a Trigger-based CDC strategy.

At ReplicaDB we are working on a Log-based CDC with Debezium implementation for continuous replication of all data events: INSERT, UPDATE and DELETE. You can check it out in our last commit https://github.com/osalvador/ReplicaDB/commit/b2fe6e713ff03f6444cc8a13d8dbef9c9c84570b

Regards.
