### ISSUE TITLE
Way to select all tables and replicate all to sink?

### ISSUE THREAD

**Issue by fcni** [osalvador/ReplicaDB#27]
Pardon me if this already exists, and I haven't found a way to do it.  But we have a large MSSQL database with many tables.  I am able to do a query for all the tables, but how do you specify to replicate all the tables into the sink?  
Thanks in advance.

**Comment by osalvador** [comment]
Hi @fcni ,

This is currently not possible. You must create a configuration file for each table you want to replicate. 

The reason is that if you want to replicate many tables with a single configuration file, the tables must have the same DDL, with the same names and compatible column types, and the replication will be sequential for each table. Also, the replication will be sequential for each table. Would these options meet your needs?

Regards!

**Comment by osalvador** [comment]
Hi @fcni ,

You can create a base configuration file (replicado.conf) with the source and sink connections and create a script with the list of all tables and overwrite the configuration with the parameters. Something like this:  

**replcaidb.conf**:

```properties
######################## ReplicadB General Options ########################
mode=complete
jobs=1
fetch.size=100
verbose=true
############################# Soruce Options ##############################
source.connect=jdbc:sqlserver://localhost:1433;database=sa
source.user=sa
source.password=<user password>
############################# Sink Options ################################
sink.connect=jdbc:postgresql://localhost:5432/public
sink.user=admin
sink.password=<user password>
```

**replicaDBMultipleTables.sh**:
```bash
#!/usr/bin/env bash

tableNames=orders,sales,stock,emp
for tableName in ${tableNames//,/ }
do
    # call your procedure/other scripts here below
    echo "Replicating ${tableName}"
    replicadb --options-file replicadb.conf --source-table "${tableName}" --sink-table "${tableName}"
done
```

Run script: 
```bash
osalvador:[~/Downloads]: ./replicaDBMultipleTables.sh
Replicating orders
./bin/replicadb --options-file replicadb.conf --source-table orders --sink-table orders
Replicating sales
./bin/replicadb --options-file replicadb.conf --source-table sales --sink-table sales
Replicating stock
./bin/replicadb --options-file replicadb.conf --source-table stock --sink-table stock
Replicating emp
./bin/replicadb --options-file replicadb.conf --source-table emp --sink-table emp
```

**Comment by fcni** [comment]
great thank you.  Sorry for the delay.
