### ISSUE TITLE
Replication not working for geometric type column 

### ISSUE THREAD

**Issue by ud20** [osalvador/ReplicaDB#31]
I have SDO_GEOMETRY column type that I am trying to replicate between oracle schemas and I see the following error. 
ERROR ReplicaTask:72 ERROR in TaskId-3 inserting data to sink table: ORA-00932: inconsistent datatypes: expected MDSYS.SDO_GEOMETRY got CHAR

ERROR ReplicaDB:101 Got exception running ReplicaDB:
java.util.concurrent.ExecutionException: java.sql.BatchUpdateException: ORA-00932: inconsistent datatypes: expected MDSYS.SDO_GEOMETRY got CHAR
I checked data and all of them are SDO_GEOMETRY type. I even tried with 1 row and its the same. Have you seen this before?

**Comment by osalvador** [comment]
Hi @ud20 ,

Could you share the DDLs of the source and sink tables and the insert statement? I'm not familiar with the SDO_GEOMETRY data type, but with this I can reproduce the exception. 

Thanks!

**Comment by ud20** [comment]
Here is the ddl. Its the same for source and sink tables just a different schema.
CREATE TABLE "TFPSYS_LOCATIONS" 
   (	"ID" VARCHAR2(17 BYTE), 
	"TITLE" VARCHAR2(300 BYTE), 
	"FIRST_CHAR" VARCHAR2(1 BYTE), 
	"LOC_TYPE" NUMBER(6,0), 
	"GEN_CAT" NUMBER(6,0), 
	"SUB_CAT" NUMBER(6,0), 
	"GEO_ID" NUMBER(10,0), 
	"ADDRESS_LINE1" VARCHAR2(100 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(100 BYTE), 
	"STATE_CODE" VARCHAR2(2 BYTE), 
	"ZIP" VARCHAR2(15 BYTE), 
	"SORT_TITLE" VARCHAR2(300 BYTE), 
	"SOURCE" VARCHAR2(5 BYTE), 
	"PHONE" VARCHAR2(18 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"CITY_SORT" VARCHAR2(100 BYTE), 
	"INST_ID" NUMBER(9,0), 
	"LOC_ID" NUMBER(9,0), 
	"TIMESTAMP" DATE, 
	"ZIP_NUMBER" NUMBER(5,0), 
	"LATITUDE" NUMBER(10,6), 
	"LONGITUDE" NUMBER(10,6), 
	"GEOM" "SDO_GEOMETRY", 
	"REMARKS" VARCHAR2(2000 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'A', 
	"INTERNAL_NOTES" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "PK_TFPSYS_LOCATIONS" PRIMARY KEY ("ID")

And here is the Insert statement 
INSERT INTO /*+APPEND_VALUES*/ uat.tfpsys_locationsrepdb6310 (ID,TITLE,FIRST_CHAR,LOC_TYPE,GEN_CAT,SUB_CAT,GEO_ID,ADDRESS_LINE1,ADDRESS_LINE2,CITY,STATE_CODE,ZIP,SORT_TITLE,SOURCE,PHONE,FAX,CITY_SORT,INST_ID,LOC_ID,TIMESTAMP,ZIP_NUMBER,LATITUDE,LONGITUDE,GEOM,REMARKS,STATUS,INTERNAL_NOTES) VALUES ( ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )

Hope this helps.

Thanks,
Udaya

**Comment by osalvador** [comment]
Hi @ud20,

I've added the `sdo_geometry` data type for Oracle Database. Could you download the latest release and try it out? 

Thanks!

**Comment by ud20** [comment]
I still see the same issue with version 10.2 and 10.5 
ERROR ReplicaTask:72 ERROR in TaskId-4 inserting data to sink table: ORA-00932: inconsistent datatypes: expected MDSYS.SDO_GEOMETRY got CHAR

**Comment by osalvador** [comment]
Hi @ud20,

`SDO_GEOMETRY` data type is tested on Oracle 11gR2 with this DDL file: https://github.com/osalvador/ReplicaDB/blob/master/src/test/resources/oracle/oracle-sdo_geometry.sql

To reproduce the exception, could share with us?: 
- Oracle database version for source and sink databases
- Replicadb config file
- DDL of source and sink tables
- Some insert statements with values for source table

**Comment by osalvador** [comment]
Close because inactivity.
