### ISSUE TITLE
Could not find or load main class org.replicadb.ReplicaDB

### ISSUE THREAD

**Issue by m-aseer** [osalvador/ReplicaDB#37]
Hi @osalvador ,

I am not able to run replicadb on centos8 .. I get the following error

./replicadb --help
Error: Could not find or load main class org.replicadb.ReplicaDB
Caused by: java.lang.ClassNotFoundException: org.replicadb.ReplicaDB

Please help.THANKS

**Comment by FrancescoTekapp** [comment]
Hi @m-aseer,

waiting for the answer of Oscar, I could suggest to you to check Java Installation and Java check ( I remember I had a similar issue with RedHat 8).

Or I if you want to speed up test the Podman (Container solution) -> https://github.com/osalvador/ReplicaDB#podman
You need Podman installed and a valid ReplicaDb configuration file in /tmp/

`sudo dnf install podman -y`

`$ podman run \
    -v /tmp/replicadb.conf:/home/replicadb/conf/replicadb.conf:Z \
    osalvador/replicadb:ubi8-latest
`

This solution is compatible with RedHat / CentOS and Selinux ready.

**Comment by osalvador** [comment]
Hi @m-aseer,

I have tested with docker centos8 and everything works fine.

```
osalvador@GalaxyOSM  ~  docker exec -it centos8 /bin/bash
[root@4a3c75a48fc3 /]# yum install java-1.8.0-openjdk.x86_64
[root@4a3c75a48fc3 /]# curl -o ReplicaDB-0.10.5.tar.gz -L "https://github.com/osalvador/ReplicaDB/releases/download/v0.10.5/ReplicaDB-0.10.5.tar.gz"
[root@4a3c75a48fc3 /]# tar -xvzf ReplicaDB-0.10.5.tar.gz
[root@4a3c75a48fc3 /]# ./bin/replicadb --help
usage: replicadb [OPTIONS]

Arguments:
    --bandwidth-throttling <KB/s>                           Adds a bandwidth cap for the replication in KB/sec.
    --fetch-size <fetch-size>                               Number of entries to read from database at once.
 -h,--help                                                  Print this help screen
....
```

Could you share which version of Java you are using and confirm that you have done the installation process of ReplicaDB correctly?

Thanks!

**Comment by m-aseer** [comment]
Hi @FrancescoTekapp

Thank you a lot for the help, unfortunately I am not familiar with podman, 

Hi @osalvador 

Here is the java version 

[root@~]# _java --version_
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

[root@ ~]# _alternatives --config java_
There are 3 programs which provide 'java'.
  Selection    Command
-----------------------------------------------
   1           java-1.8.0-openjdk.x86_64 (/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.302.b08-0.el8_4.x86_64/jre/bin/java)
*+ 2           /usr/java/jdk-17/bin/java
   3           java-11-openjdk.x86_64 (/usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.el8_4.x86_64/bin/java)



I traced configure-replicadb to get the proper values for all replicadb environment variables. Then I did export them from the outer shell and made them persistent ... Once the environment variables are defined, it works like charm ..

For some reason the environment variables are not there when configure-replicadb is called from replicadb

This application works like charm .. I really thank you guys for making this available for people to use it. I do not know what you have written inside it but it works effortlessly ....

One more question, 
There is no command line argument to schedule replication for example every 10 min. I should use crontab, please confirm.

Thanks again

**Comment by osalvador** [comment]
Hi @m-aseer 

Thanks to you for your acknowledgements. 

Could you share what exactly you did to get the `configure-replicadb` working? I'm trying to reproduce the issue. 

About your last question; 

> There is no command line argument to schedule replication for example every 10 min. I should use crontab, please confirm.

No, there is no command line to schedule the replication. You should use crontab. At the moment, ReplicaDB is focused on Batch replication.
