### ISSUE TITLE
 Oracle Replication Fails 

### ISSUE THREAD

**Issue by rajkirandav** [osalvador/ReplicaDB#4]
Hi ,I am trying to replicate Oracle DB (source and destination ) both Oracle .Replication fails with below error .Not sure if this has something to do with class path ? 

[root@B-Wallet-Lab ~]# replicadb --mode=complete -j=1 --source-connect=jdbc:oracle:thin:@10.0.0.137:1521:BPLORA --source-user=btapp --source-password=btapp --source-table=POSTPAID_MAST --sink-connect=jdbc:oracle:thin:@10.0.0.42:1521:BPLORA --source-user=mfs --source-password=mfs --sink-table=POSTPAID_MAST
2020-01-15 20:28:42,650 INFO  ReplicaDB:43 Running ReplicaDB version: 0.6.0
2020-01-15 20:28:42,662 ERROR ReplicaDB:83 Got exception running ReplicaDB:
java.lang.RuntimeException: Could not load db driver class: oracle.jdbc.OracleDriver
        at org.replicadb.manager.SqlManager.makeSinkConnection(SqlManager.java:237) ~[ReplicaDB-0.6.0.jar:0.6.0]
        at org.replicadb.manager.SqlManager.getConnection(SqlManager.java:97) ~[ReplicaDB-0.6.0.jar:0.6.0]
        at org.replicadb.manager.SqlManager.truncateTable(SqlManager.java:375) ~[ReplicaDB-0.6.0.jar:0.6.0]
        at org.replicadb.manager.SqlManager.preSinkTasks(SqlManager.java:437) ~[ReplicaDB-0.6.0.jar:0.6.0]
        at org.replicadb.ReplicaDB.main(ReplicaDB.java:60) [ReplicaDB-0.6.0.jar:0.6.0]
2020-01-15 20:28:42,666 INFO  ReplicaDB:102 Total process time: 34ms

**Comment by osalvador** [comment]
Hi @rajkirandav,

This is a common mistake, as you can read in the README.md: 

> **JDBC Drivers**
> You can use ReplicaDB with any JDBC-compliant database. First, download the appropriate JDBC driver for the type of database you want to use, and install the .jar file in the `$REPLICADB_HOME/lib` directory on your client machine. Each driver `.jar` file also has a specific driver class which defines the entry-point to the driver.

Therefore, you must download oracle drivers from https://www.oracle.com/database/technologies/appdev/jdbc-downloads.html and install at least the ojdbc8.jar in the `$REPLICADB_HOME/lib` directory (if the databases have diferent encoding you'll need the orai18n.jar too)

**Comment by rajkirandav** [comment]
Thanks ..shall give a try ..can u also include couple of examples in your articles for Oracle to Oracle replication both standalone and Oracle RAC?

**Comment by osalvador** [comment]
Hi @rajkirandav, I'm working on create a configuration wizard web page for all compatible source and sink systems.

**Comment by rajkirandav** [comment]
Thanks .That would be great..Is there any way by which replicad can run as background process and do the job automatically at configured time as against running via  cron ?

**Comment by osalvador** [comment]
Hi @rajkirandav,

There are a lot of schedulers in the market. Replicadb is made with the batch (or microbatch) replication in mind, therefore you should to scheduler replicadb process, at least at the moment. 

I'm thinking on add CDC capabilities using Debezium embbedded conector (MySQL, PostgreSQL, SQLServer, MongoDB) but now, I'm centered on extend batch capatilities.

**Comment by osalvador** [comment]
Hi @rajkirandav 

Replicadb configuration wizard is now available: https://osalvador.github.io/ReplicaDB/wizard/index.html
