### ISSUE TITLE
Oracle Greek Characters Problem

### ISSUE THREAD

**Issue by MichalisDBA** [osalvador/ReplicaDB#61]
Hello.

We try to migrate data from an Oracle table to MySQL.

In Oracle the NLS_CHARACTERSET is EL8ISO8859P7

select * from nls_database_parameters  where parameter='NLS_CHARACTERSET';

The problem is, the connections and the data transfer happens BUT in the MySQL table the data are empty, only fields with numbers are showing.

I think it has something to do with the character encoding.

Is there a way to force the jdbc:oracle from Oracle source to use EL8ISO8859P7 NLS_CHARACTERSET?

I tried something like this

source.connect=jdbc:oracle:thin:@<IP>:<PORT>:<SERVER>?characterEncoding=EL8ISO8859P7 OR ?characterEncoding=utf8

but the same result. Blank fields.

**Comment by osalvador** [comment]
Hi @MichalisDBA,

To reproduce the issue, we need some data: 
- Source database version
- Sink database version
- DDL of source and sink tables
- The ReplicaDB options file you are using to configure the replication

Thanks!

**Comment by MichalisDBA** [comment]
Source database version: Oracle 9i
Sink database version: Percona 8
DDL Source:
`CREATE TABLE TESTING.TEST
(
  TRX_NUMBER                     VARCHAR2(20 BYTE),
  CUSTOMER_NAME                  VARCHAR2(50 BYTE),
  CUSTOMER_NUMBER                VARCHAR2(30 BYTE),
  CUSTOMER_AFM                   VARCHAR2(50 BYTE),
  SITE                           NUMBER(15),
  ODOS                           VARCHAR2(240 BYTE),
  ARITHMOS                       VARCHAR2(240 BYTE),
  PHONE                          VARCHAR2(240 BYTE),
  CITY                           VARCHAR2(60 BYTE),
  MEGALOS_PELATHS                VARCHAR2(1 BYTE),
  SYMBASH                        VARCHAR2(30 BYTE),
  CUSTOMER_CATEGORY              VARCHAR2(30 BYTE),
  CUSTOMER_CATEGORY_DESCRIPTION  VARCHAR2(240 BYTE),
  ITEM                           VARCHAR2(40 BYTE),
  ITEM_DESC                      VARCHAR2(240 BYTE),
  ITEM_CATEGORY                  VARCHAR2(40 BYTE),
  ITEM_CATEGORY_DESCR            VARCHAR2(240 BYTE),
  EXPENSE_ACC                    VARCHAR2(25 BYTE),
  QUANTITY_INVOICED              NUMBER,
  UNIT_SELLING_PRICE             NUMBER,
  ESODO                          NUMBER,
  TRX_DATE                       DATE,
  TRX_YEAR                       VARCHAR2(4 BYTE),
  TRX_MONTH                      VARCHAR2(2 BYTE),
  ACCOUNT                        VARCHAR2(25 BYTE),
  PERIFEREIA                     VARCHAR2(25 BYTE),
  MON_SYN                        VARCHAR2(25 BYTE),
  TAX_GRAFEIO                    VARCHAR2(25 BYTE),
  TAX_AMOUNT                     NUMBER,
  TAX_ACC                        VARCHAR2(25 BYTE),
  TAX_PERIFEREIA                 VARCHAR2(25 BYTE),
  TAX_MON_SYN                    VARCHAR2(25 BYTE),
  TAX_TAX_GRAFEIO                VARCHAR2(25 BYTE),
  CUSTOMER_TRX_LINE_ID           NUMBER(15),
  CUSTOMER_TRX_ID                NUMBER(15),
  REC_ACC                        VARCHAR2(25 BYTE),
  TYPE                           VARCHAR2(20 BYTE),
  TYPE_DESCRIPTION               VARCHAR2(80 BYTE),
  OROI_PLIROMIS                  VARCHAR2(15 BYTE),
  INTERFACE_HEADER_ATTRIBUTE1    VARCHAR2(30 BYTE),
  MAILSTXNID                     VARCHAR2(30 BYTE),
  THYRIDA                        VARCHAR2(3 CHAR),
  CREATED_BY_USER                VARCHAR2(100 BYTE),
  CREATED_BY_USER_DESCRIPTION    VARCHAR2(240 BYTE),
  FOREASID                       VARCHAR2(100 BYTE),
  FOREASDESC                     VARCHAR2(100 BYTE),
  PRIORITY                       NUMBER,
  CNTR                           VARCHAR2(22 BYTE),
  CNTRDESC                       VARCHAR2(100 BYTE),
  TIMH_MONADAS                   NUMBER,
  VAROS_SE_GR                    NUMBER,
  MEGETHOS                       VARCHAR2(6 BYTE),
  TYPOPOIHSH                     VARCHAR2(16 BYTE),
  TAKSINOMHSH                    VARCHAR2(16 BYTE),
  PROOR_SAKWN                    VARCHAR2(9 BYTE),
  EPILOGH_EPIDOSHS_OEXDP         VARCHAR2(7 BYTE),
  KWDIKOS_XWRAS_EKSWTERIKOY      VARCHAR2(3 CHAR),
  CAT_ALLHLOGRAFIAS              VARCHAR2(8 BYTE),
  POSO_POU_PROSMETR_STON_TZIRO   NUMBER,
  POSO_POU_PROSMETR_STON_OGKO    NUMBER,
  PER_ENTYPOY                    VARCHAR2(3 BYTE),
  COMMENTS                       VARCHAR2(1760 BYTE),
  DEST                           VARCHAR2(3 BYTE),
  DESTNAME                       VARCHAR2(50 BYTE),
  PER_ENTYPOY_GGE                VARCHAR2(11 BYTE),
  TRX_SOURCE                     VARCHAR2(30 BYTE),
  AR_PAROXHS                     VARCHAR2(150 BYTE)
)
TABLESPACE FNDD
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;`

DDL Sink:
`CREATE TABLE `TEST` (
  `TRX_NUMBER` varchar(20) DEFAULT NULL,
  `CUSTOMER_NAME` varchar(50) DEFAULT NULL,
  `CUSTOMER_NUMBER` varchar(30) DEFAULT NULL,
  `CUSTOMER_AFM` varchar(50) DEFAULT NULL,
  `SITE` bigint DEFAULT NULL,
  `ODOS` varchar(240) DEFAULT NULL,
  `ARITHMOS` varchar(240) DEFAULT NULL,
  `PHONE` varchar(240) DEFAULT NULL,
  `CITY` varchar(60) DEFAULT NULL,
  `MEGALOS_PELATHS` varchar(1) DEFAULT NULL,
  `SYMBASH` varchar(30) DEFAULT NULL,
  `CUSTOMER_CATEGORY` varchar(30) DEFAULT NULL,
  `CUSTOMER_CATEGORY_DESCRIPTION` varchar(240) DEFAULT NULL,
  `ITEM` varchar(40) DEFAULT NULL,
  `ITEM_DESC` varchar(240) DEFAULT NULL,
  `ITEM_CATEGORY` varchar(40) DEFAULT NULL,
  `ITEM_CATEGORY_DESCR` varchar(240) DEFAULT NULL,
  `EXPENSE_ACC` varchar(25) DEFAULT NULL,
  `QUANTITY_INVOICED` double DEFAULT NULL,
  `UNIT_SELLING_PRICE` double DEFAULT NULL,
  `ESODO` double DEFAULT NULL,
  `TRX_DATE` datetime DEFAULT NULL,
  `TRX_YEAR` varchar(4) DEFAULT NULL,
  `TRX_MONTH` varchar(2) DEFAULT NULL,
  `ACCOUNT` varchar(25) DEFAULT NULL,
  `PERIFEREIA` varchar(25) DEFAULT NULL,
  `MON_SYN` varchar(25) DEFAULT NULL,
  `TAX_GRAFEIO` varchar(25) DEFAULT NULL,
  `TAX_AMOUNT` double DEFAULT NULL,
  `TAX_ACC` varchar(25) DEFAULT NULL,
  `TAX_PERIFEREIA` varchar(25) DEFAULT NULL,
  `TAX_MON_SYN` varchar(25) DEFAULT NULL,
  `TAX_TAX_GRAFEIO` varchar(25) DEFAULT NULL,
  `CUSTOMER_TRX_LINE_ID` bigint DEFAULT NULL,
  `CUSTOMER_TRX_ID` bigint DEFAULT NULL,
  `REC_ACC` varchar(25) DEFAULT NULL,
  `TYPE` varchar(20) DEFAULT NULL,
  `TYPE_DESCRIPTION` varchar(80) DEFAULT NULL,
  `OROI_PLIROMIS` varchar(15) DEFAULT NULL,
  `INTERFACE_HEADER_ATTRIBUTE1` varchar(30) DEFAULT NULL,
  `MAILSTXNID` varchar(30) DEFAULT NULL,
  `THYRIDA` varchar(3) DEFAULT NULL,
  `CREATED_BY_USER` varchar(100) DEFAULT NULL,
  `CREATED_BY_USER_DESCRIPTION` varchar(240) DEFAULT NULL,
  `FOREASID` varchar(100) DEFAULT NULL,
  `FOREASDESC` varchar(100) DEFAULT NULL,
  `PRIORITY` double DEFAULT NULL,
  `CNTR` varchar(22) DEFAULT NULL,
  `CNTRDESC` varchar(100) DEFAULT NULL,
  `TIMH_MONADAS` double DEFAULT NULL,
  `VAROS_SE_GR` double DEFAULT NULL,
  `MEGETHOS` varchar(6) DEFAULT NULL,
  `TYPOPOIHSH` varchar(16) DEFAULT NULL,
  `TAKSINOMHSH` varchar(16) DEFAULT NULL,
  `PROOR_SAKWN` varchar(9) DEFAULT NULL,
  `EPILOGH_EPIDOSHS_OEXDP` varchar(7) DEFAULT NULL,
  `KWDIKOS_XWRAS_EKSWTERIKOY` varchar(3) DEFAULT NULL,
  `CAT_ALLHLOGRAFIAS` varchar(8) DEFAULT NULL,
  `POSO_POU_PROSMETR_STON_TZIRO` double DEFAULT NULL,
  `POSO_POU_PROSMETR_STON_OGKO` double DEFAULT NULL,
  `PER_ENTYPOY` varchar(3) DEFAULT NULL,
  `COMMENTS` varchar(1760) DEFAULT NULL,
  `DEST` varchar(3) DEFAULT NULL,
  `DESTNAME` varchar(50) DEFAULT NULL,
  `PER_ENTYPOY_GGE` varchar(11) DEFAULT NULL,
  `TRX_SOURCE` varchar(30) DEFAULT NULL,
  `AR_PAROXHS` varchar(150) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`

Oracle 9i NLS Parameters:
`PARAMETER,VALUE
NLS_LANGUAGE,AMERICAN
NLS_TERRITORY,AMERICA
NLS_CURRENCY,$
NLS_ISO_CURRENCY,AMERICA
NLS_NUMERIC_CHARACTERS,.,
NLS_CHARACTERSET,EL8ISO8859P7
NLS_CALENDAR,GREGORIAN
NLS_DATE_FORMAT,DD-MON-RR
NLS_DATE_LANGUAGE,AMERICAN
NLS_SORT,BINARY
NLS_TIME_FORMAT,HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT,DD-MON-RR HH.MI.SSXFF AM
NLS_TIME_TZ_FORMAT,HH.MI.SSXFF AM TZR
NLS_TIMESTAMP_TZ_FORMAT,DD-MON-RR HH.MI.SSXFF AM TZR
NLS_DUAL_CURRENCY,$
NLS_COMP,BINARY
NLS_LENGTH_SEMANTICS,BYTE
NLS_NCHAR_CONV_EXCP,FALSE
NLS_NCHAR_CHARACTERSET,AL16UTF16
NLS_RDBMS_VERSION,9.2.0.6.0
`

The Config:

`######################## ReplicadB General Options ########################
mode=complete
jobs=1
#fetch.size=1
verbose=true
############################# Soruce Options ##############################
source.connect=jdbc:oracle:thin:@ip:port:sid
source.user=TEST
source.password=TEST
source.table=TESTING.TEST
############################# Sink Options ################################
sink.connect=jdbc:mysql://IP:PORT/DB
sink.user=TEST
sink.password=TEST
sink.table=DB.TEST
`

**Comment by osalvador** [comment]
Hi @MichalisDBA,

I can't reproduce the issue as I don't have an Oracle 9i DB for testing. But I think the problem is in the Oracle JDBC driver version. 

ReplicaDB uses Oracle drivers `ojdbc8-19.3.0.0.jar` and for Oracle 9i you need to use version 11.2.0.4 `ojdbc6-11.2.0.4.jar`: https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc6/11.2.0.4/

In addition, the Oracle library that contains the functions for internationalisation is orai18n, which allows character set translation. You can download it here: https://repo1.maven.org/maven2/com/oracle/database/nls/orai18n/11.2.0.4/

My recommendation for ReplicaDB to work correctly with Oracle9i (XMLTYPE, BLOB, Oracle RAC...) is to remove from the `~/replicadb/lib` folder all oracle version `19.3.0` drivers and replace them with their corresponding `11.2.0.4`: https://repo1.maven.org/maven2/com/oracle/database/

```bash
~/replicadb/lib > ls -ltr *19.3.0*
-rw-r--r--  1 oscar.salvador  staff  1918463  7 oct 17:54 xmlparserv2-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff   262664  7 oct 17:54 xdb-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff  1680074  7 oct 17:54 ucp-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff    29205  7 oct 17:54 simplefan-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff   306854  7 oct 17:54 osdt_core-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff   205154  7 oct 17:54 osdt_cert-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff  1661488  7 oct 17:54 orai18n-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff   306004  7 oct 17:54 oraclepki-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff   144681  7 oct 17:54 ons-19.3.0.0.jar
-rw-r--r--  1 oscar.salvador  staff  4210517  7 oct 17:54 ojdbc8-19.3.0.0.jar
```

**Comment by MichalisDBA** [comment]
@osalvador 
Thank you very much. I replaced them all as you said and now it works!
