### ISSUE TITLE
Unable to Install ReplicaDB

### ISSUE THREAD

**Issue by kriakris** [osalvador/ReplicaDB#7]
![image](https://user-images.githubusercontent.com/61589163/75637170-be7e4a80-5c78-11ea-9e49-c79134a2ba05.png)

![image](https://user-images.githubusercontent.com/61589163/75637194-ea99cb80-5c78-11ea-992f-38bd93f099e2.png)

**Comment by osalvador** [comment]
Hi @kriakris,

ReplicaDB is a command line tool that does not require installation, just download and execute. 

On Windows systems you must execute the script `bin\replicadb.cmd` to run the application, from the Windows `CMD` utility. 

![Captura de pantalla 2020-03-02 a las 10 27 05](https://user-images.githubusercontent.com/7385607/75663478-29c41e80-5c71-11ea-89aa-2a72c6f19d82.png)
