### ISSUE TITLE
Substr of certain columns from source database

### ISSUE THREAD

**Issue by kuoth86** [osalvador/ReplicaDB#82]
Is there a way to copy the first 5 letters from column OAAA of table OTEST in an Oracle database, to column PAAA of table PTEST in a PostgreSQL database?
I've tried to complete it in conf without success:
............
source.query="SELECT SUBSTR(OAAA,1,5) FROM OTEST.OAAA"
............

p.s. Great tool, by the way. Really awesome.

**Comment by kuoth86** [comment]
Never mind. I found another way to achieve it. Thanks anyway.

**Comment by osalvador** [comment]
Hi @kuoth86,

Could you share how you solve your issue? I see that the query is correct. 

Thanks.

**Comment by kuoth86** [comment]
Putting substr(oaaa,1,5) in source.columns instead solved my problem. Thanks
