### ISSUE TITLE
Strange Oracle Date Bug

### ISSUE THREAD

**Issue by MichalisDBA** [osalvador/ReplicaDB#95]
**Describe the bug**
Hello. I found a strange bug while trying to replicate a table that has a DATE column with specific values.
I tried it on two different oracle databases, versions. 9 & 11.

**To Reproduce**

Source table DDL:
```
CREATE TABLE MIKE_TEST_1
(
  NUM      NUMBER(20)                           NOT NULL,
  TRXTIME  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
```
Sink table DDL:
```
CREATE TABLE MIKE_TEST_2
(
  NUM      NUMBER(20)                           NOT NULL,
  TRXTIME  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
```

ReplicaDB configuration `options-file`. :
```
######################## ReplicadB General Options ########################
mode=complete
jobs=1
fetch.size=100
verbose=true
############################# Soruce Options ##############################
source.connect=jdbc:oracle:thin:@192.168.1.10:1521:mike
source.user=username
source.password=password
source.query=SELECT * FROM MIKE_TEST_1
############################# Sink Options ################################
sink.connect=jdbc:oracle:thin:@192.168.1.10:1521:mike
sink.user=username
sink.password=password
sink.table=MIKE_TEST_2
sink.disable.truncate=false
```

Insert this on source table MIKE_TEST_1:
```
INSERT INTO MIKE_TEST_1 (NUM, TRXTIME)
VALUES (1, TO_DATE('1-1-1900 01:40:00', 'DD/MM/YYYY HH:MI:ss'));
```
Run the replicadb with the above config.

Check sink table MIKE_TEST_2, instead of having values

```
NUM	TRXTIME
1	1-1-1900 01:40:00
```

The values are

```
NUM	TRXTIME
1	1-1-1900 02:05:08
```

**Expected behavior**
Values at table MIKE_TEST_2 must be

```
NUM	TRXTIME
1	1-1-1900 01:40:00
```

**Additional context**

The strange thing is that if you insert at MIKE_TEST_1

```
INSERT INTO MIKE_TEST_1 (NUM, TRXTIME)
VALUES (1, TO_DATE('1-1-1901 01:40:00', 'DD/MM/YYYY HH:MI:ss'));
```

The values at MIKE_TEST_2 sink table after running replicadb are ok

MIKE_TEST_1
```
NUM	TRXTIME
1	1-1-1901 01:40:00
```

MIKE_TEST_2
```
NUM	TRXTIME
1	1-1-1901 01:40:00
```

So far i traced the following scenarios

Source Table: MIKE_TEST_1

```
NUM	TRXTIME
1	1-1-1900 01:45:00
2	1-1-1900 01:40:00
3	1-1-1900 01:38:00
4	1-1-1900 01:35:00
5	1-1-1900 01:30:00
6	1-1-1901 01:40:00
```

Sink Table: MIKE_TEST_2

```
NUM	TRXTIME
1	1-1-1900 02:10:08
2	1-1-1900 02:05:08
3	1-1-1900 02:03:08
4	1-1-1900 02:00:08
5	1-1-1900 01:30:00
6	1-1-1901 01:40:00
```

**Comment by osalvador** [comment]
Hi @MichalisDBA ,

Sorry for the delay, I've been very busy these days. 

The Oracle 9i database is deprecated by Oracle some years ago. I think the problem comes from driver incompatibility between Oracle 9i and JDBC 19c driver. 

You can try this two things:
- Download the non-Oracle version of ReplicaDB, which comes without Oracle drivers (ReplicaDB-0.12.3-no-oracle.tar.gz), and find and use the Oracle 9i drivers, putting them in the `$REPLICADB_HOME/lib` folder. 

- Transform the date to CHAR, using a custom query and let Oracle cast the String to Date in the sink column.

```
######################## ReplicadB General Options ########################
mode=complete
jobs=1
fetch.size=100
verbose=true
############################# Soruce Options ##############################
source.connect=jdbc:oracle:thin:@192.168.1.10:1521:mike
source.user=username
source.password=password
source.query=SELECT NUM, TO_CHAR(TRXTIME, 'YYYY-MM-DD HH24:MI:SS') as TRXTIME FROM MIKE_TEST_1
############################# Sink Options ################################
sink.connect=jdbc:oracle:thin:@192.168.1.10:1521:mike
sink.user=username
sink.password=password
sink.table=MIKE_TEST_2
sink.disable.truncate=false
```

Hope this help!

**Comment by MichalisDBA** [comment]
@osalvador 

Thanks for the reply.

I have had replaced the drivers when i asked in a previous issue already

https://github.com/osalvador/ReplicaDB/issues/61

I will try the Transform to CHAR and see if it's working.

Thanks.

**Comment by MichalisDBA** [comment]
@osalvador 

I tried with TO_CHAR and also CONVERT from MSSQL and works. Now the data are identical.

```
CONVERT(VARCHAR(19), TRxTime, 20) as TRxTime
```


Thank you very much
